# -*- coding: utf-8 -*-
"""MAQA2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TM5MrRl-EOEggP2PnuNGIVwPXDrlnVaA
"""

# Bayesian Volumetric Input Panel
# @markdown Enter your CAD specs. Use 'r' before strings to avoid SyntaxWarnings.

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. User Input Fields ---
radius_nominal = 50.0 # @param {type:"number"}
radius_tolerance = 0.5 # @param {type:"number"}
height_nominal = 120.0 # @param {type:"number"}
height_tolerance = 1.2 # @param {type:"number"}
sample_size = 10000 # @param {type:"slider", min:1000, max:50000, step:1000}

# --- 2. Statistical Logic ---
def generate_priors(r_nom, r_tol, h_nom, h_tol, n):
    # Why / 3? Because in Metrology, the tolerance range usually represents the 3-Sigma limits of a process.
    sigma_r = r_tol / 3
    sigma_h = h_tol / 3

    # Generate random samples (The "Prior" Beliefs)
    R_samples = np.random.normal(r_nom, sigma_r, n)
    H_samples = np.random.normal(h_nom, sigma_h, n)

    return R_samples, H_samples, sigma_r, sigma_h

# Run the generator
R_priors, H_priors, s_r, s_h = generate_priors(
    radius_nominal, radius_tolerance, height_nominal, height_tolerance, sample_size
)

# --- 3. Visualization ---
sns.set_theme(style="white")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Plot Radius with 'raw' string r"..." to fix LaTeX issues
sns.histplot(R_priors, kde=True, color="dodgerblue", ax=ax1)
ax1.set_title(r"Radius Prior: $\mathcal{N}( \mu=%.1f, \sigma=%.3f )$" % (radius_nominal, s_r))
ax1.set_xlabel("Radius (mm)")

# Plot Height
sns.histplot(H_priors, kde=True, color="forestgreen", ax=ax2)
ax2.set_title(r"Height Prior: $\mathcal{N}( \mu=%.1f, \sigma=%.3f )$" % (height_nominal, s_h))
ax2.set_xlabel("Height (mm)")

plt.tight_layout()
plt.show()

print(f"Input Stage Complete. Generated {sample_size} stochastic samples.")

# Monte Carlo Volume Propagation

import pandas as pd

def propagate_uncertainty(r_samples, h_samples):
    # The Core Formula applied to all 10,000+ samples at once (Vectorization)
    V_samples = np.pi * (r_samples**2) * h_samples

    # Convert to Liters for easier reading (optional, depends on chamber size)
    # 1,000,000 mm^3 = 1 Liter
    V_samples_L = V_samples / 1_000_000

    return V_samples_L

# Calculate Volumes
V_dist = propagate_uncertainty(R_priors, H_priors)

# --- Visualization ---
plt.figure(figsize=(10, 6))
sns.histplot(V_dist, kde=True, color="purple", bins=50)

# Calculate Mean and Standard Deviation of the Result
v_mean = np.mean(V_dist)
v_std = np.std(V_dist)

# Add visual markers for the Mean and Confidence Intervals
plt.axvline(v_mean, color='red', linestyle='--', label=f'Mean: {v_mean:.3f}L')
plt.axvline(v_mean - 2*v_std, color='orange', linestyle=':', label='95% Lower Bound')
plt.axvline(v_mean + 2*v_std, color='orange', linestyle=':', label='95% Upper Bound')

plt.title(r"Propagated Volume Distribution: $V \sim P(V|R,H)$")
plt.xlabel("Volume (Liters)")
plt.ylabel("Frequency")
plt.legend()
plt.show()

print(f"Calculation Complete.")
print(f"The 'Expected' Volume is {v_mean:.4f} Liters.")
print(f"The Uncertainty (Standard Deviation) is {v_std:.4f} Liters.")

# MCMC Sampling
# This cell 'discovers' the volume by running a Markov Chain.

import pymc as pm
import arviz as az

# 1. Create the Bayesian Model Environment
with pm.Model() as chamber_model:
    # Defining our Priors (The 'Clouds' from Step 1)
    # We use 'mu' and 'sigma' from our previous inputs
    R = pm.Normal("Radius", mu=radius_nominal, sigma=s_r)
    H = pm.Normal("Height", mu=height_nominal, sigma=s_h)

    # The Deterministic Rule (The Formula)
    # We track this variable so we can see the 'discovered' Volume
    V = pm.Deterministic("Volume", (np.pi * R**2 * H) / 1_000_000) # In Liters

    # 2. The MCMC Sampler (The Detective starts walking)
    # 'draws' is how many steps each scout takes
    # 'chains' is how many independent scouts we send out
    trace = pm.sample(draws=2000, chains=4, return_inferencedata=True)

# 3. Visualizing the "Thinking Process" (The Trace Plot)
az.plot_trace(trace, var_names=["Radius", "Height"])
plt.tight_layout()
plt.show()

print("MCMC Sampling Complete!")

#  Final Metrological Report
# Run this to see the 95% Credible Interval and Six Sigma Compliance.

import arviz as az

# 1. Extract the Volume samples from the MCMC Trace
post_vol = trace.posterior["Volume"].values.flatten()

# 2. Calculate the 95% High Density Interval (HDI)
hdi = az.hdi(trace, var_names=["Volume"], hdi_prob=0.95).Volume.values

# 3. Metrological Stats
v_mu = np.mean(post_vol)
v_sig = np.std(post_vol)
v_min, v_max = hdi[0], hdi[1]

# 4. Visualization
plt.figure(figsize=(10, 6))
az.plot_posterior(trace, var_names=["Volume"], color="gold")
plt.title("Posterior Volume Distribution (The 'True' Knowledge)")
plt.show()

# --- The Report Output ---
print("-" * 30)
print("METROLOGY SUMMARY REPORT")
print("-" * 30)
print(f"Mean Expected Volume:  {v_mu:.4f} L")
print(f"Standard Uncertainty:  {v_sig:.4f} L")
print(f"95% Credible Interval: [{v_min:.4f} L to {v_max:.4f} L]")
print("-" * 30)

# Optional: Six Sigma Logic
# Let's assume the chamber 'fails' if it's 1% away from the mean
limit_upper = v_mu * 1.01
z_score = (limit_upper - v_mu) / v_sig

print(f"Six Sigma Score (Z):   {z_score:.2f}")
if z_score >= 6:
    print("STATUS: ✅ World-Class Precision (Six Sigma Compliant)")
elif z_score >= 3:
    print("STATUS: ⚠️ Industrial Standard (Three Sigma)")
else:
    print("STATUS: ❌ High Risk (High Uncertainty)")

# The Shrinkage of Uncertainty
# This creates a comparison plot showing how the MCMC refined your understanding.

# 1. Create a "Simplified" Prior Volume for comparison
# (Taking a random slice of our original Monte Carlo result)
prior_vol = V_dist

# 2. Plotting the Comparison
plt.figure(figsize=(12, 6))

sns.kdeplot(prior_vol, label="Initial CAD Guess (Prior)", color="gray", linestyle="--", fill=True, alpha=0.1)
sns.kdeplot(post_vol, label="MCMC Refined (Posterior)", color="purple", fill=True, alpha=0.3)

plt.axvline(v_mu, color='purple', lw=2, label=f'Final Mean: {v_mu:.3f}L')

plt.title("The Bayesian 'Shrinkage': How the Computer Refined the Volume", fontsize=14)
plt.xlabel("Volume (Liters)")
plt.ylabel("Probability Density")
plt.legend()
plt.grid(axis='y', alpha=0.3)

plt.show()

print("Analysis Complete.")
print(f"You have moved from a raw tolerance of ±{radius_tolerance}mm ")
print(f"to a high-precision Credible Interval of {v_max - v_min:.5f} Liters.")